### ISSUE TITLE
Bullet list

### ISSUE THREAD

**Issue by bmen** [chardso/fruit-culture-fruit-farming#6]
With a bulleted list you have to start with a `-` followed by a `space` and then a key point name

Right:
```
- Point 1
- Point 2
```

Wrong:
```
-Point 1
-Point 2
```

**Comment by chardso** [comment]
Thank very much ,I followed the guideline u gave me and i have adjusted
accordingly, and may be u can go through again.God bless u with more
knowledge.

**Comment by chardso** [comment]
Thank you very for that accurate ,I followed ur guide,and corrected.

**Comment by timmwille** [comment]
nice, so we can close this issue, thx @chardso
